"""ASS subtitle writer for lyric video generation.

Converts LRC or timestamped lyrics into ASS (Advanced SubStation Alpha)
format for FFmpeg burn-in via the libass filter. Reimplemented from the
documented ASS spec — no GPL dependency.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

STYLE_PRESETS: Dict[str, Dict[str, str]] = {
    "default": {
        "font": "Arial",
        "size": "48",
        "primary": "&H00FFFFFF",
        "secondary": "&H000000FF",
        "outline": "&H00000000",
        "back": "&H00000000",
        "border": "2",
        "shadow": "1",
        "alignment": "2",
    },
    "neon": {
        "font": "Consolas",
        "size": "52",
        "primary": "&H00FF00FF",
        "secondary": "&H000000FF",
        "outline": "&H00FF00FF",
        "back": "&H00000000",
        "border": "3",
        "shadow": "0",
        "alignment": "2",
    },
    "minimal": {
        "font": "Helvetica",
        "size": "40",
        "primary": "&H00FFFFFF",
        "secondary": "&H000000FF",
        "outline": "&H00000000",
        "back": "&H00000000",
        "border": "1",
        "shadow": "0",
        "alignment": "2",
    },
    "bold": {
        "font": "Impact",
        "size": "56",
        "primary": "&H00FFFFFF",
        "secondary": "&H000000FF",
        "outline": "&H00000000",
        "back": "&H00000000",
        "border": "3",
        "shadow": "2",
        "alignment": "2",
    },
}

_LRC_TIME_RE = re.compile(r"\[(\d{1,2}):(\d{2})(?:[.:](\d{1,3}))?\]")
_LRC_META_RE = re.compile(r"^\[(?:ti|ar|al|by|offset|length|re|ve):", re.IGNORECASE)


def parse_lrc(path: Path) -> List[Dict[str, float]]:
    """Parse an LRC file into a list of {time, text} dicts.

    Args:
        path: Path to .lrc file.

    Returns:
        List of dicts with 'time' (float seconds) and 'text' (str).
    """
    if not path.exists():
        raise FileNotFoundError(f"LRC file not found: {path}")

    lines: List[Dict[str, float]] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        raw_line = raw_line.strip()
        if not raw_line:
            continue
        if _LRC_META_RE.match(raw_line):
            continue

        match = _LRC_TIME_RE.match(raw_line)
        if not match:
            continue

        minutes = int(match.group(1))
        seconds = int(match.group(2))
        frac_str = match.group(3) or "0"
        if len(frac_str) == 1:
            frac = int(frac_str) * 100
        elif len(frac_str) == 2:
            frac = int(frac_str)
        else:
            frac = int(frac_str) // 10

        time = minutes * 60 + seconds + frac / 100.0
        text = raw_line[match.end():].strip()
        lines.append({"time": time, "text": text})

    return lines


def _format_ass_time(seconds: float) -> str:
    """Format seconds as ASS timestamp: H:MM:SS.cc"""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centis = int((seconds - int(seconds)) * 100)
    return f"{hours}:{minutes:02d}:{secs:02d}.{centis:02d}"


def _build_ass_header(style: str, width: int = 1280, height: int = 720) -> str:
    """Build the ASS header (Script Info + Styles)."""
    if style not in STYLE_PRESETS:
        raise KeyError(f"Unknown style preset: {style}")

    p = STYLE_PRESETS[style]
    return (
        "[Script Info]\n"
        "; Generated by Music-AI-Toolshop\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {width}\n"
        f"PlayResY: {height}\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,{p['font']},{p['size']},{p['primary']},"
        f"{p['secondary']},{p['outline']},{p['back']},0,0,0,0,100,100,0,0,"
        f"1,{p['border']},{p['shadow']},{p['alignment']},40,40,60,1\n"
    )


def _build_dialogue_line(
    start: float, end: float, text: str, style: str = "Default"
) -> str:
    """Build a single ASS Dialogue line."""
    start_ts = _format_ass_time(start)
    end_ts = _format_ass_time(end)
    escaped = text.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
    escaped = escaped.replace("\n", "\\N")
    return f"Dialogue: 0,{start_ts},{end_ts},{style},,0,0,0,,{escaped}"


def generate_ass(
    lyrics: List[Dict[str, float]],
    output_path: Path,
    style: str = "default",
    resolution: Tuple[int, int] = (1280, 720),
    default_duration: float = 4.0,
) -> Path:
    """Generate an ASS subtitle file from parsed lyrics.

    Args:
        lyrics: List of dicts with 'time' (float) and 'text' (str).
        output_path: Where to write the .ass file.
        style: Style preset name (default, neon, minimal, bold).
        resolution: (width, height) for PlayResX/Y.
        default_duration: Default line duration in seconds (used for last line).

    Returns:
        Path to the written .ass file.
    """
    width, height = resolution
    header = _build_ass_header(style, width, height)

    events = "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"

    for i, entry in enumerate(lyrics):
        start = entry["time"]
        if i + 1 < len(lyrics):
            end = lyrics[i + 1]["time"]
        else:
            end = start + default_duration
        events += _build_dialogue_line(start, end, entry["text"]) + "\n"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header + "\n" + events, encoding="utf-8")
    return output_path


def lrc_to_ass(
    lrc_path: Path,
    output_path: Path,
    style: str = "default",
    resolution: Tuple[int, int] = (1280, 720),
    default_duration: float = 4.0,
) -> Path:
    """Convert an LRC file directly to ASS format.

    Args:
        lrc_path: Path to .lrc file.
        output_path: Where to write the .ass file.
        style: Style preset name.
        resolution: (width, height) for PlayResX/Y.
        default_duration: Default line duration in seconds.

    Returns:
        Path to the written .ass file.
    """
    lyrics = parse_lrc(lrc_path)
    return generate_ass(lyrics, output_path, style, resolution, default_duration)
