//! Fingerprint Database Module
//!
//! SQLite-based storage for audio fingerprints with similarity search.
//! Tracks audio variants and their processing relationships.

use crate::reverse_engineer::spectral::SpectralFeatures;
use rusqlite::{Connection, Result as SqlResult, params, OptionalExtension};
use ndarray::Array1;
use std::path::Path;

/// Audio fingerprint for storage and comparison
#[derive(Debug, Clone, PartialEq)]
pub struct Fingerprint {
    /// Unique ID (auto-generated by database)
    pub id: Option<i64>,
    /// File path or identifier
    pub file_path: String,
    /// Track name or label
    pub track_name: String,
    /// Variant type (original, stem, remix, master, etc.)
    pub variant_type: String,
    /// Parent fingerprint ID (for tracking processing chains)
    pub parent_id: Option<i64>,
    /// Spectral features as feature vector
    pub features: SpectralFeatures,
    /// Sample rate
    pub sample_rate: u32,
    /// Duration in seconds
    pub duration_sec: f32,
    /// File hash for deduplication
    pub file_hash: String,
    /// Processing chain description (if known)
    pub processing_chain: Option<String>,
}

/// Fingerprint database with similarity search
pub struct FingerprintDatabase {
    conn: Connection,
}

impl FingerprintDatabase {
    /// Open or create database at given path
    pub fn open<P: AsRef<Path>>(path: P) -> SqlResult<Self> {
        let conn = Connection::open(path)?;
        let db = Self { conn };
        db.init_schema()?;
        Ok(db)
    }
    
    /// Create in-memory database (for testing)
    pub fn open_in_memory() -> SqlResult<Self> {
        let conn = Connection::open_in_memory()?;
        let db = Self { conn };
        db.init_schema()?;
        Ok(db)
    }
    
    /// Initialize database schema
    fn init_schema(&self) -> SqlResult<()> {
        self.conn.execute_batch(
            "CREATE TABLE IF NOT EXISTS fingerprints (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                file_path TEXT NOT NULL,
                track_name TEXT NOT NULL,
                variant_type TEXT NOT NULL,
                parent_id INTEGER,
                centroid REAL,
                rolloff REAL,
                flux REAL,
                flatness REAL,
                crest_factor REAL,
                rms_db REAL,
                peak_db REAL,
                lufs_estimate REAL,
                zcr REAL,
                bandwidth REAL,
                sample_rate INTEGER,
                duration_sec REAL,
                file_hash TEXT NOT NULL UNIQUE,
                processing_chain TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (parent_id) REFERENCES fingerprints(id)
            );
            
            CREATE INDEX IF NOT EXISTS idx_track_name ON fingerprints(track_name);
            CREATE INDEX IF NOT EXISTS idx_variant ON fingerprints(variant_type);
            CREATE INDEX IF NOT EXISTS idx_parent ON fingerprints(parent_id);
            CREATE INDEX IF NOT EXISTS idx_hash ON fingerprints(file_hash);
            "
        )
    }
    
    /// Insert fingerprint into database
    pub fn insert(&self, fingerprint: &Fingerprint) -> SqlResult<i64> {
        self.conn.execute(
            "INSERT INTO fingerprints (
                file_path, track_name, variant_type, parent_id,
                centroid, rolloff, flux, flatness, crest_factor,
                rms_db, peak_db, lufs_estimate, zcr, bandwidth,
                sample_rate, duration_sec, file_hash, processing_chain
            ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18)
            ON CONFLICT(file_hash) DO UPDATE SET
                file_path = excluded.file_path,
                track_name = excluded.track_name,
                centroid = excluded.centroid,
                rolloff = excluded.rolloff,
                flux = excluded.flux,
                flatness = excluded.flatness,
                crest_factor = excluded.crest_factor,
                rms_db = excluded.rms_db,
                peak_db = excluded.peak_db,
                lufs_estimate = excluded.lufs_estimate,
                zcr = excluded.zcr,
                bandwidth = excluded.bandwidth,
                sample_rate = excluded.sample_rate,
                duration_sec = excluded.duration_sec",
            params![
                fingerprint.file_path,
                fingerprint.track_name,
                fingerprint.variant_type,
                fingerprint.parent_id,
                fingerprint.features.spectral_centroid,
                fingerprint.features.spectral_rolloff,
                fingerprint.features.spectral_flux,
                fingerprint.features.spectral_flatness,
                fingerprint.features.crest_factor,
                fingerprint.features.rms_db,
                fingerprint.features.peak_db,
                fingerprint.features.lufs_estimate,
                fingerprint.features.zero_crossing_rate,
                fingerprint.features.bandwidth,
                fingerprint.sample_rate,
                fingerprint.duration_sec,
                fingerprint.file_hash,
                fingerprint.processing_chain,
            ],
        )?;
        
        Ok(self.conn.last_insert_rowid())
    }
    
    /// Get fingerprint by ID
    pub fn get(&self, id: i64) -> SqlResult<Option<Fingerprint>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, file_path, track_name, variant_type, parent_id,
                    centroid, rolloff, flux, flatness, crest_factor,
                    rms_db, peak_db, lufs_estimate, zcr, bandwidth,
                    sample_rate, duration_sec, file_hash, processing_chain
             FROM fingerprints WHERE id = ?1"
        )?;
        
        let fingerprint = stmt.query_row([id], |row| {
            Ok(Fingerprint {
                id: Some(row.get(0)?),
                file_path: row.get(1)?,
                track_name: row.get(2)?,
                variant_type: row.get(3)?,
                parent_id: row.get(4)?,
                features: SpectralFeatures {
                    spectral_centroid: row.get(5)?,
                    spectral_rolloff: row.get(6)?,
                    spectral_flux: row.get(7)?,
                    spectral_flatness: row.get(8)?,
                    crest_factor: row.get(9)?,
                    rms_db: row.get(10)?,
                    peak_db: row.get(11)?,
                    lufs_estimate: row.get(12)?,
                    zero_crossing_rate: row.get(13)?,
                    bandwidth: row.get(14)?,
                },
                sample_rate: row.get(15)?,
                duration_sec: row.get(16)?,
                file_hash: row.get(17)?,
                processing_chain: row.get(18)?,
            })
        }).optional()?;
        
        Ok(fingerprint)
    }
    
    /// Find fingerprints by track name
    pub fn find_by_track(&self, track_name: &str) -> SqlResult<Vec<Fingerprint>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, file_path, track_name, variant_type, parent_id,
                    centroid, rolloff, flux, flatness, crest_factor,
                    rms_db, peak_db, lufs_estimate, zcr, bandwidth,
                    sample_rate, duration_sec, file_hash, processing_chain
             FROM fingerprints WHERE track_name = ?1 ORDER BY created_at"
        )?;
        
        let fingerprints = stmt.query_map([track_name], |row| {
            Ok(Fingerprint {
                id: Some(row.get(0)?),
                file_path: row.get(1)?,
                track_name: row.get(2)?,
                variant_type: row.get(3)?,
                parent_id: row.get(4)?,
                features: SpectralFeatures {
                    spectral_centroid: row.get(5)?,
                    spectral_rolloff: row.get(6)?,
                    spectral_flux: row.get(7)?,
                    spectral_flatness: row.get(8)?,
                    crest_factor: row.get(9)?,
                    rms_db: row.get(10)?,
                    peak_db: row.get(11)?,
                    lufs_estimate: row.get(12)?,
                    zero_crossing_rate: row.get(13)?,
                    bandwidth: row.get(14)?,
                },
                sample_rate: row.get(15)?,
                duration_sec: row.get(16)?,
                file_hash: row.get(17)?,
                processing_chain: row.get(18)?,
            })
        })?
        .filter_map(Result::ok)
        .collect();
        
        Ok(fingerprints)
    }
    
    /// Find similar fingerprints using cosine similarity
    pub fn find_similar(&self, query: &Fingerprint, threshold: f32, limit: usize) -> SqlResult<Vec<(Fingerprint, f32)>> {
        // Get all fingerprints for comparison
        let mut stmt = self.conn.prepare(
            "SELECT id, file_path, track_name, variant_type, parent_id,
                    centroid, rolloff, flux, flatness, crest_factor,
                    rms_db, peak_db, lufs_estimate, zcr, bandwidth,
                    sample_rate, duration_sec, file_hash, processing_chain
             FROM fingerprints WHERE id != ?1"
        )?;
        
        let query_id = query.id.unwrap_or(-1);
        let candidates: Vec<Fingerprint> = stmt.query_map([query_id], |row| {
            Ok(Fingerprint {
                id: Some(row.get(0)?),
                file_path: row.get(1)?,
                track_name: row.get(2)?,
                variant_type: row.get(3)?,
                parent_id: row.get(4)?,
                features: SpectralFeatures {
                    spectral_centroid: row.get(5)?,
                    spectral_rolloff: row.get(6)?,
                    spectral_flux: row.get(7)?,
                    spectral_flatness: row.get(8)?,
                    crest_factor: row.get(9)?,
                    rms_db: row.get(10)?,
                    peak_db: row.get(11)?,
                    lufs_estimate: row.get(12)?,
                    zero_crossing_rate: row.get(13)?,
                    bandwidth: row.get(14)?,
                },
                sample_rate: row.get(15)?,
                duration_sec: row.get(16)?,
                file_hash: row.get(17)?,
                processing_chain: row.get(18)?,
            })
        })?
        .filter_map(Result::ok)
        .collect();
        
        // Compute cosine similarity for each candidate
        let query_vector = Self::to_vector(&query.features);
        let mut results: Vec<(Fingerprint, f32)> = candidates
            .into_iter()
            .map(|fp| {
                let fp_vector = Self::to_vector(&fp.features);
                let similarity = Self::cosine_similarity(&query_vector, &fp_vector);
                (fp, similarity)
            })
            .filter(|(_, sim)| *sim >= threshold)
            .collect();
        
        // Sort by similarity (descending) and limit
        results.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        results.truncate(limit);
        
        Ok(results)
    }
    
    /// Get processing chain for a track (all variants in order)
    pub fn get_processing_chain(&self, root_id: i64) -> SqlResult<Vec<Fingerprint>> {
        let mut chain = Vec::new();
        let mut current_id = Some(root_id);
        
        while let Some(id) = current_id {
            if let Some(fp) = self.get(id)? {
                current_id = fp.parent_id;
                chain.push(fp);
            } else {
                break;
            }
        }
        
        // Reverse to get root -> leaf order
        chain.reverse();
        Ok(chain)
    }
    
    /// Delete fingerprint by ID
    pub fn delete(&self, id: i64) -> SqlResult<bool> {
        let rows = self.conn.execute(
            "DELETE FROM fingerprints WHERE id = ?1",
            [id],
        )?;
        Ok(rows > 0)
    }
    
    /// Get database statistics
    pub fn stats(&self) -> SqlResult<(usize, usize)> {
        let total: i64 = self.conn.query_row(
            "SELECT COUNT(*) FROM fingerprints",
            [],
            |row| row.get(0)
        )?;
        
        let tracks: i64 = self.conn.query_row(
            "SELECT COUNT(DISTINCT track_name) FROM fingerprints",
            [],
            |row| row.get(0)
        )?;
        
        Ok((total as usize, tracks as usize))
    }
    
    /// Convert features to vector for similarity computation
    fn to_vector(features: &SpectralFeatures) -> Array1<f32> {
        // Normalize features to comparable ranges
        Array1::from(vec![
            features.spectral_centroid / 10000.0,  // Normalize to ~0-2 range
            features.spectral_rolloff / 20000.0,  // Normalize to ~0-1 range
            features.spectral_flux / 100.0,       // Normalize
            features.spectral_flatness,
            features.crest_factor / 20.0,         // Normalize
            (features.rms_db + 60.0) / 60.0,      // Normalize from -60..0 to 0..1
            (features.peak_db + 60.0) / 60.0,
            (features.lufs_estimate + 60.0) / 60.0,
            features.zero_crossing_rate,
            features.bandwidth / 5000.0,        // Normalize
        ])
    }
    
    /// Compute cosine similarity between two vectors (0-1 range, 1 = identical)
    fn cosine_similarity(a: &Array1<f32>, b: &Array1<f32>) -> f32 {
        if a.len() != b.len() || a.is_empty() {
            return 0.0;
        }
        
        let dot = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum::<f32>();
        let norm_a = a.iter().map(|x| x * x).sum::<f32>().sqrt();
        let norm_b = b.iter().map(|x| x * x).sum::<f32>().sqrt();
        
        if norm_a > 0.0 && norm_b > 0.0 {
            (dot / (norm_a * norm_b)).clamp(0.0, 1.0)
        } else {
            0.0
        }
    }
    
    /// Compute simple hash for file content (placeholder - real implementation would hash audio data)
    pub fn compute_hash(file_path: &str) -> String {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};
        
        let mut hasher = DefaultHasher::new();
        file_path.hash(&mut hasher);
        format!("{:016x}", hasher.finish())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    fn create_test_fingerprint(name: &str, variant: &str, centroid: f32) -> Fingerprint {
        Fingerprint {
            id: None,
            file_path: format!("/audio/{}.wav", name),
            track_name: name.to_string(),
            variant_type: variant.to_string(),
            parent_id: None,
            features: SpectralFeatures {
                spectral_centroid: centroid,
                spectral_rolloff: 5000.0,
                spectral_flux: 10.0,
                spectral_flatness: 0.5,
                crest_factor: 12.0,
                rms_db: -12.0,
                peak_db: -6.0,
                lufs_estimate: -14.0,
                zero_crossing_rate: 0.1,
                bandwidth: 2000.0,
            },
            sample_rate: 44100,
            duration_sec: 180.0,
            file_hash: FingerprintDatabase::compute_hash(&format!("{}_{}", name, variant)),
            processing_chain: None,
        }
    }
    
    #[test]
    fn test_database_creation() {
        let db = FingerprintDatabase::open_in_memory().unwrap();
        let (total, tracks) = db.stats().unwrap();
        assert_eq!(total, 0);
        assert_eq!(tracks, 0);
    }
    
    #[test]
    fn test_insert_and_retrieve() {
        let db = FingerprintDatabase::open_in_memory().unwrap();
        
        let fp = create_test_fingerprint("Test Track", "original", 1000.0);
        let id = db.insert(&fp).unwrap();
        
        let retrieved = db.get(id).unwrap().expect("Should retrieve fingerprint");
        assert_eq!(retrieved.track_name, "Test Track");
        assert_eq!(retrieved.variant_type, "original");
        assert!((retrieved.features.spectral_centroid - 1000.0).abs() < 0.01);
    }
    
    #[test]
    fn test_find_by_track() {
        let db = FingerprintDatabase::open_in_memory().unwrap();
        
        let fp1 = create_test_fingerprint("Track A", "original", 1000.0);
        let fp2 = create_test_fingerprint("Track A", "remix", 2000.0);
        let fp3 = create_test_fingerprint("Track B", "original", 1500.0);
        
        db.insert(&fp1).unwrap();
        db.insert(&fp2).unwrap();
        db.insert(&fp3).unwrap();
        
        let results = db.find_by_track("Track A").unwrap();
        assert_eq!(results.len(), 2);
    }
    
    #[test]
    fn test_similarity_search() {
        let db = FingerprintDatabase::open_in_memory().unwrap();
        
        // Create fingerprints with different centroids
        let fp1 = create_test_fingerprint("Track 1", "original", 1000.0);
        let fp2 = create_test_fingerprint("Track 2", "original", 1050.0); // Similar
        let fp3 = create_test_fingerprint("Track 3", "original", 8000.0);  // Very different
        
        let id1 = db.insert(&fp1).unwrap();
        db.insert(&fp2).unwrap();
        db.insert(&fp3).unwrap();
        
        let query = db.get(id1).unwrap().expect("Should get query");
        let similar = db.find_similar(&query, 0.95, 10).unwrap();
        
        // Should find fp2 as similar, not fp3
        assert!(!similar.is_empty());
        let found_names: Vec<String> = similar.iter().map(|(fp, _)| fp.track_name.clone()).collect();
        assert!(found_names.contains(&"Track 2".to_string()));
        assert!(!found_names.contains(&"Track 3".to_string()));
    }
    
    #[test]
    fn test_processing_chain() {
        let db = FingerprintDatabase::open_in_memory().unwrap();
        
        // Create a chain: original -> stem -> remix
        let mut original = create_test_fingerprint("My Song", "original", 1000.0);
        let orig_id = db.insert(&original).unwrap();
        original.id = Some(orig_id);
        
        let mut stem = create_test_fingerprint("My Song", "vocal_stem", 1200.0);
        stem.parent_id = Some(orig_id);
        let stem_id = db.insert(&stem).unwrap();
        
        let mut remix = create_test_fingerprint("My Song", "remix", 1500.0);
        remix.parent_id = Some(stem_id);
        let remix_id = db.insert(&remix).unwrap();
        
        let chain = db.get_processing_chain(remix_id).unwrap();
        assert_eq!(chain.len(), 3);
        assert_eq!(chain[0].variant_type, "original");
        assert_eq!(chain[1].variant_type, "vocal_stem");
        assert_eq!(chain[2].variant_type, "remix");
    }
    
    #[test]
    fn test_cosine_similarity() {
        let a = Array1::from(vec![1.0, 0.0, 0.0]);
        let b = Array1::from(vec![1.0, 0.0, 0.0]);
        assert!((FingerprintDatabase::cosine_similarity(&a, &b) - 1.0).abs() < 0.001);
        
        let c = Array1::from(vec![0.0, 1.0, 0.0]);
        assert!(FingerprintDatabase::cosine_similarity(&a, &c) < 0.001);
    }
    
    #[test]
    fn test_hash_uniqueness() {
        let hash1 = FingerprintDatabase::compute_hash("file1.wav");
        let hash2 = FingerprintDatabase::compute_hash("file2.wav");
        let hash3 = FingerprintDatabase::compute_hash("file1.wav");
        
        assert_ne!(hash1, hash2);
        assert_eq!(hash1, hash3);
    }
    
    #[test]
    fn test_duplicate_insertion() {
        let db = FingerprintDatabase::open_in_memory().unwrap();
        
        let fp = create_test_fingerprint("Dup Test", "original", 1000.0);
        let id1 = db.insert(&fp).unwrap();
        let id2 = db.insert(&fp).unwrap(); // Same hash, should update
        
        // Should return same ID due to upsert
        assert_eq!(id1, id2);
        
        let count = db.stats().unwrap().0;
        assert_eq!(count, 1);
    }
}
